### ISSUE TITLE
cc-number and cc-cvc attributes produce TypeError unless cc-type is included

### ISSUE THREAD

**Issue by maxmalynowsky** [bendrucker/angular-credit-cards#25]
The documentation for your app is a little unclear about how to properly implement it. Using the examples in the readme, I received two TypeErrors that were due to a missing cc-type attribute. This was also replicated when hosting the plunkr code locally. You list this attribute as optional, but I'm not sure this is the case, can you verify?

Additionally, it would be useful to have a complete quick start example to copy-paste from as included below.

Broken Code
```html
<form name="paymentForm">
  <input type="text" ng-model="card.number" name="cardNumber" cc-number cc-eager-type />
  <input type="text" ng-model="card.cvc" cc-cvc />
  <div cc-exp>
    <input ng-model="card.exp_month" cc-exp-month />
    <input ng-model="card.exp_year" cc-exp-year />
  </div>
</form>
```

Working Code
```html
<form name="paymentForm">
    <input type="text" ng-model="card.number" name="cardNumber" cc-type="cardType" cc-number cc-eager-type />
    <input type="text" ng-model="card.cvc" cc-type="cardNumber.$ccType" cc-cvc />
    <div cc-exp>
      <input ng-model="card.exp_month" cc-exp-month />
      <input ng-model="card.exp_year" cc-exp-year />
    </div>
  </form>
```

cc-number Error
```
TypeError: Cannot read property 'exp' of undefined
    at ng.config.$provide.decorator.watchFnToHumanReadableString (<anonymous>:703:19)
    at Scope.ng.config.$provide.decorator.$delegate.__proto__.$watch (<anonymous>:735:28)
    at module.exports.compile (http://192.168.33.10/static/libs/angular-credit-cards/release/angular-credit-cards.js:461:15)
    at invokeLinkFn (http://192.168.33.10/static/libs/angular/angular.js:8258:9)
    at nodeLinkFn (http://192.168.33.10/static/libs/angular/angular.js:7768:11)
    at compositeLinkFn (http://192.168.33.10/static/libs/angular/angular.js:7117:13)
    at nodeLinkFn (http://192.168.33.10/static/libs/angular/angular.js:7763:24)
    at compositeLinkFn (http://192.168.33.10/static/libs/angular/angular.js:7117:13)
    at compositeLinkFn (http://192.168.33.10/static/libs/angular/angular.js:7120:13)
    at publicLinkFn (http://192.168.33.10/static/libs/angular/angular.js:6996:30) <input type="text" ng-model="card.number" name="cardNumber" cc-number="" cc-eager-type="" class="ng-pristine ng-untouched ng-valid" pattern="[0-9]*">
```

cc-cvc Error
```
TypeError: Cannot read property 'exp' of undefined
    at ng.config.$provide.decorator.watchFnToHumanReadableString (<anonymous>:703:19)
    at Scope.ng.config.$provide.decorator.$delegate.__proto__.$watch (<anonymous>:735:28)
    at module.exports.compile (http://192.168.33.10/static/libs/angular-credit-cards/release/angular-credit-cards.js:318:15)
    at invokeLinkFn (http://192.168.33.10/static/libs/angular/angular.js:8258:9)
    at nodeLinkFn (http://192.168.33.10/static/libs/angular/angular.js:7768:11)
    at compositeLinkFn (http://192.168.33.10/static/libs/angular/angular.js:7117:13)
    at nodeLinkFn (http://192.168.33.10/static/libs/angular/angular.js:7763:24)
    at compositeLinkFn (http://192.168.33.10/static/libs/angular/angular.js:7117:13)
    at compositeLinkFn (http://192.168.33.10/static/libs/angular/angular.js:7120:13)
    at publicLinkFn (http://192.168.33.10/static/libs/angular/angular.js:6996:30) <input type="text" ng-model="card.cvc" cc-cvc="" class="ng-pristine ng-untouched ng-valid" maxlength="4" pattern="[0-9]*">
```

**Comment by bendrucker** [comment]
Pushed a patch that I think should resolve what you're seeing. If it doesn't please reproduce it in a way that I can go run (tests are ideal, but plunkr et al is ok too).

PRs are super welcome to clarify the docs. I'm starting to plan out an example with angular-credit-cards and angular-stripe paired, as well as a few other components. Not too keen on offering something and inviting people to copy and paste. I want people to understand what they're doing.
